# Generated by Django 4.0.4 on 2022-07-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='favorite',
        ),
    ]
