# Generated by Django 4.0.4 on 2022-07-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_favoritemovies'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='genres',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
