# Generated by Django 4.0.4 on 2022-07-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movies_genres'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteMovies',
        ),
    ]
